name: Tests
on: [push, pull_request]
jobs:
  install-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '10.16.0'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test